/* Shared WOD library — used by the WOD Finder (wods.html) and the WOD picker
 * on a WOD training day (workout.html). Add as many as you want.
 * Format: [name, format, equipment[], description, category]
 * category: "girl" | "hero" | "open" | "other"
 * Rx loads shown are the men's prescription — scale to you.
 * Prescriptions authored from public-domain CrossFit benchmark facts. */
window.WODS = [
  // ============ THE GIRLS (CrossFit benchmark) ============
  ["Fran","For Time",["Barbell","Pull-up bar"],"21-15-9: thrusters (95) + pull-ups. The classic sprint — go unbroken if you can.","girl"],
  ["Helen","RFT",["Kettlebell","Pull-up bar"],"3 rounds: 400 m run, 21 KB swings (53), 12 pull-ups.","girl"],
  ["Grace","For Time",["Barbell"],"30 clean & jerks for time (135).","girl"],
  ["Isabel","For Time",["Barbell"],"30 snatches for time (135).","girl"],
  ["Elizabeth","For Time",["Barbell","Bodyweight"],"21-15-9: power cleans (135) + ring dips.","girl"],
  ["Amanda","For Time",["Pull-up bar","Barbell"],"9-7-5: muscle-ups + squat snatches (135).","girl"],
  ["Cindy","AMRAP",["Pull-up bar","Bodyweight"],"20 min AMRAP: 5 pull-ups, 10 push-ups, 15 air squats.","girl"],
  ["Mary","AMRAP",["Bodyweight"],"20 min AMRAP: 5 HSPU, 10 pistols, 15 pull-ups (scale freely).","girl"],
  ["Annie","For Time",["Jump rope"],"50-40-30-20-10: double-unders + sit-ups.","girl"],
  ["Jackie","For Time",["Rower","Barbell","Pull-up bar"],"1000 m row, 50 thrusters (45), 30 pull-ups.","girl"],
  ["Diane","For Time",["Barbell"],"21-15-9: deadlift (225) + handstand push-ups (scale HSPU).","girl"],
  ["Karen","For Time",["Wall ball"],"150 wall balls (20) for time. Pace the sets.","girl"],
  ["Nancy","RFT",["Barbell"],"5 rounds: 400 m run + 15 overhead squats (95).","girl"],
  ["Barbara","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 20 pull-ups, 30 push-ups, 40 sit-ups, 50 squats — rest 3 min between rounds.","girl"],
  ["Angie","For Time",["Pull-up bar","Bodyweight"],"100 pull-ups, 100 push-ups, 100 sit-ups, 100 squats — finish each before moving on.","girl"],
  ["Chelsea","EMOM",["Pull-up bar","Bodyweight"],"EMOM 30 min: 5 pull-ups, 10 push-ups, 15 squats.","girl"],
  ["Eva","RFT",["Kettlebell","Pull-up bar"],"5 rounds: 800 m run, 30 KB swings (70), 30 pull-ups. A grinder.","girl"],
  ["Lynne","RFT",["Barbell","Pull-up bar"],"5 rounds, no time cap: bodyweight bench press (max reps) + max pull-ups. Rest as needed.","girl"],
  ["Nicole","AMRAP",["Pull-up bar"],"20 min AMRAP: 400 m run, then max pull-ups (note the number each round).","girl"],
  ["Linda","For Time",["Barbell"],"\"3 bars of death\" 10-9-8…1: deadlift (1.5x bw), bench press (bw), clean (0.75x bw).","girl"],
  ["Kelly","RFT",["Box","Wall ball"],"5 rounds: 400 m run, 30 box jumps (24), 30 wall balls (20).","girl"],
  ["Nasty Girls","RFT",["Bodyweight","Pull-up bar","Barbell"],"3 rounds: 50 squats, 7 muscle-ups, 10 hang power cleans (135).","girl"],
  ["Gwen","For Time",["Barbell"],"Clean & jerk 15-12-9, same load all sets, touch-and-go at floor, rest as needed. You pick the weight.","girl"],
  ["Maggie","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 20 handstand push-ups, 40 pull-ups, 60 alternating pistols.","girl"],
  ["Candy","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 20 pull-ups, 40 push-ups, 60 squats.","girl"],
  ["Marguerita","RFT",["Bodyweight"],"50 rounds: 1 burpee, 1 push-up, 1 jumping jack, 1 sit-up, 1 handstand.","girl"],
  ["Megan","For Time",["Kettlebell","Jump rope"],"21-15-9: burpees, KB swings (53), double-unders.","girl"],

  // ============ HERO WODs ============
  ["Murph","For Time",["Pull-up bar","Bodyweight"],"1 mi run, 100 pull-ups, 200 push-ups, 300 squats, 1 mi run. Vest optional. Partition the middle.","hero"],
  ["DT","RFT",["Barbell"],"5 rounds: 12 deadlifts, 9 hang power cleans, 6 push jerks (155).","hero"],
  ["The Chief","AMRAP",["Barbell","Bodyweight"],"5 cycles of 3 min AMRAP: 3 power cleans (135), 6 push-ups, 9 squats. 1 min rest between.","hero"],
  ["JT","For Time",["Bodyweight"],"21-15-9: handstand push-ups, ring dips, push-ups.","hero"],
  ["Randy","For Time",["Barbell"],"75 power snatches for time (75).","hero"],
  ["Chad","For Time",["Box"],"1000 box step-ups (20 in). Wear a ruck/vest (45) if able.","hero"],
  ["Glen","For Time",["Barbell","Pull-up bar"],"30 clean & jerks (135), 1 mi run, 10 rope climbs, 1 mi run, 100 burpees.","hero"],
  ["Holleyman","RFT",["Wall ball","Barbell"],"30 rounds: 5 wall balls (20), 3 HSPU, 1 power clean (225).","hero"],
  ["Wittman","RFT",["Kettlebell","Barbell","Box"],"7 rounds: 15 KB swings (53), 15 power cleans (95), 15 box jumps (24).","hero"],
  ["Daniel","For Time",["Pull-up bar","Barbell"],"50 pull-ups, 400 m run, 21 thrusters (95), 800 m run, 21 thrusters, 400 m run, 50 pull-ups.","hero"],
  ["Josh","For Time",["Barbell","Pull-up bar"],"21 OHS (95) + 42 pull-ups, 15 OHS + 30 pull-ups, 9 OHS + 18 pull-ups.","hero"],
  ["Roy","RFT",["Barbell","Box","Pull-up bar"],"5 rounds: 15 deadlifts (225), 20 box jumps (24), 25 pull-ups.","hero"],
  ["Ryan","RFT",["Pull-up bar","Bodyweight"],"5 rounds: 7 muscle-ups, 21 burpees (chest to deck).","hero"],
  ["Nate","AMRAP",["Pull-up bar","Kettlebell"],"20 min AMRAP: 2 muscle-ups, 4 HSPU, 8 KB swings (70).","hero"],
  ["Tommy V","For Time",["Barbell"],"21 thrusters (115), 12 rope climbs, 15 thrusters, 9 rope climbs, 9 thrusters, 6 rope climbs.","hero"],
  ["Jason","For Time",["Bodyweight","Pull-up bar"],"100 squats, 5 muscle-ups, 75 squats, 10 MU, 50 squats, 15 MU, 25 squats, 20 MU.","hero"],
  ["Loredo","RFT",["Bodyweight"],"6 rounds: 24 squats, 24 push-ups, 24 walking lunges, 400 m run.","hero"],
  ["Bradshaw","RFT",["Barbell","Pull-up bar","Jump rope"],"10 rounds: 3 HSPU, 6 deadlifts (225), 12 pull-ups, 24 double-unders.","hero"],
  ["McGhee","AMRAP",["Barbell","Box"],"30 min AMRAP: 5 deadlifts (275), 13 push-ups, 9 box jumps (24).","hero"],
  ["The Seven","RFT",["Barbell","Pull-up bar","Kettlebell"],"7 rounds: 7 HSPU, 7 thrusters (135), 7 knees-to-elbow, 7 deadlifts (245), 7 burpees, 7 KB swings (70), 7 pull-ups.","hero"],
  ["Coe","RFT",["Barbell","Bodyweight"],"10 rounds: 10 thrusters (95), 10 ring push-ups.","hero"],
  ["Hammer","RFT",["Barbell","Pull-up bar"],"5 rounds: 5 power cleans (135), 10 front squats, 5 jerks, 20 pull-ups. Rest 90 s between.","hero"],
  ["Badger","RFT",["Barbell","Pull-up bar"],"3 rounds: 30 squat cleans (95), 30 pull-ups, 800 m run.","hero"],
  ["Joshie","RFT",["Dumbbells","Pull-up bar"],"3 rounds: 21 DB squat snatches right (40), 21 L-pull-ups, 21 DB squat snatches left, 21 L-pull-ups.","hero"],
  ["Danny","AMRAP",["Box","Barbell","Pull-up bar"],"20 min AMRAP: 30 box jumps (24), 20 push press (115), 30 pull-ups.","hero"],
  ["Hansen","RFT",["Kettlebell","Bodyweight"],"5 rounds: 30 KB swings (70), 30 burpees, 30 GHD/anchored sit-ups.","hero"],
  ["Tyler","RFT",["Pull-up bar","Barbell"],"5 rounds: 7 muscle-ups, 21 sumo deadlift high-pulls (95).","hero"],
  ["Garrett","RFT",["Bodyweight","Pull-up bar"],"3 rounds: 75 squats, 25 ring HSPU, 25 L-pull-ups.","hero"],
  ["War Frank","RFT",["Pull-up bar","Bodyweight"],"3 rounds: 25 muscle-ups, 100 squats, 35 GHD/anchored sit-ups.","hero"],
  ["Paul","RFT",["Jump rope","Pull-up bar","Barbell"],"5 rounds: 50 double-unders, 35 knees-to-elbow, 20-yd overhead walk (185).","hero"],
  ["Jerry","For Time",["Rower"],"1 mi run, 2 km row, 1 mi run. Pure engine.","hero"],
  ["Rankel","AMRAP",["Barbell","Kettlebell","Pull-up bar"],"20 min AMRAP: 6 deadlifts (225), 7 burpee pull-ups, 10 KB swings (70), 200 m run.","hero"],
  ["Bull","RFT",["Jump rope","Barbell","Pull-up bar"],"2 rounds: 200 double-unders, 50 OHS (135), 50 pull-ups, 1 mi run.","hero"],
  ["Severin","For Time",["Pull-up bar","Bodyweight"],"50 strict pull-ups, 100 push-ups, 5 km run. Vest (20) if able.","hero"],
  ["Helton","RFT",["Dumbbells","Bodyweight"],"3 rounds: 800 m run, 30 DB squat cleans (50), 30 burpees.","hero"],
  ["Jack","AMRAP",["Barbell","Kettlebell","Box"],"20 min AMRAP: 10 push press (115), 10 KB swings (53), 10 box jumps (24).","hero"],
  ["Forrest","RFT",["Pull-up bar","Bodyweight"],"3 rounds: 20 L-pull-ups, 30 toes-to-bar, 40 burpees, 800 m run.","hero"],
  ["Manion","RFT",["Barbell"],"7 rounds: 400 m run, 29 back squats (135).","hero"],
  ["Whitten","RFT",["Kettlebell","Box","Wall ball"],"5 rounds: 22 KB swings (53), 22 box jumps (24), 400 m run, 22 burpees, 22 wall balls (20).","hero"],
  ["Klepto","RFT",["Box","Barbell","Bodyweight"],"4 rounds: 27 box jumps (24), 20 burpees, 11 squat cleans (145).","hero"],
  ["Zimmerman","AMRAP",["Pull-up bar","Barbell","Bodyweight"],"25 min AMRAP: 11 chest-to-bar pull-ups, 2 deadlifts (315), 10 HSPU.","hero"],
  ["Erin","RFT",["Dumbbells","Pull-up bar"],"5 rounds: 15 DB split cleans (40 each), 21 pull-ups.","hero"],
  ["Mr Joshua","RFT",["Bodyweight","Barbell"],"5 rounds: 400 m run, 30 GHD/anchored sit-ups, 15 deadlifts (250).","hero"],
  ["Griff","For Time",["Bodyweight"],"800 m run, 400 m run backward, 800 m run, 400 m run backward.","hero"],
  ["Arnie","For Time",["Kettlebell"],"With one KB (53): 21 Turkish get-ups R, 50 swings, 21 OHS L, 50 swings, 21 OHS R, 50 swings, 21 TGU L.","hero"],
  ["Michael","RFT",["Bodyweight"],"3 rounds: 800 m run, 50 back extensions, 50 sit-ups.","hero"],
  ["Nutts","Chipper",["Bodyweight","Barbell","Box","Pull-up bar","Wall ball","Jump rope"],"10 HSPU, 15 deadlifts (250), 25 box jumps (30), 50 pull-ups, 100 wall balls (20), 200 double-unders, 400 m run with a 45-lb plate.","hero"],
  ["Lumberjack 20","Chipper",["Barbell","Kettlebell","Pull-up bar","Box","Dumbbells","Bodyweight"],"400 m run between each: 20 deadlifts (275), 20 KB swings (70), 20 OHS (115), 20 burpees, 20 C2B pull-ups, 20 box jumps (24), 20 DB squat cleans (45).","hero"],
  ["Adam Brown","RFT",["Barbell","Box","Wall ball"],"2 rounds: 24 deadlifts (295), 24 box jumps (24), 24 wall balls (20), 24 bench press (195), 24 box jumps, 24 wall balls, 24 cleans (145).","hero"],
  ["Hamilton","RFT",["Rower","Bodyweight","Pull-up bar"],"3 rounds: 1000 m row, 50 push-ups, 1000 m run, 50 pull-ups.","hero"],
  ["Holbrook","Interval",["Barbell","Pull-up bar","Bodyweight"],"10 rounds: 5 thrusters (115), 10 pull-ups, 100 m sprint — rest 1 min between rounds.","hero"],
  ["Blake","RFT",["Barbell","Box","Wall ball","Bodyweight"],"4 rounds: 100-ft overhead walking lunge (45 plate), 30 box jumps (24), 20 wall balls (20), 10 HSPU.","hero"],
  ["Wood","Interval",["Box","Barbell","Bodyweight"],"5 rounds: 400 m run, 10 burpee box jumps (24), 10 SDHP (95), 10 thrusters (95) — rest 1 min.","hero"],
  ["Abbate","For Time",["Barbell","Bodyweight"],"1 mi run, 21 clean & jerks (155), 800 m run, 21 clean & jerks (155), 1 mi run.","hero"],
  ["Riley","For Time",["Bodyweight"],"1.5 mi run, 150 burpees, 1.5 mi run. Vest (20) if able.","hero"],
  ["Marco","RFT",["Pull-up bar","Barbell","Bodyweight"],"3 rounds: 21 pull-ups, 15 HSPU, 9 thrusters (135).","hero"],
  ["Jared","RFT",["Pull-up bar","Bodyweight"],"4 rounds: 800 m run, 40 pull-ups, 70 push-ups.","hero"],
  ["Luce","RFT",["Pull-up bar","Bodyweight"],"3 rounds (20-lb vest): 1000 m run, 10 muscle-ups, 100 squats.","hero"],
  ["Small","RFT",["Rower","Box","Bodyweight"],"3 rounds: 1000 m row, 50 burpees, 50 box jumps (24), 800 m run.","hero"],
  ["Weston","RFT",["Rower","Dumbbells"],"5 rounds: 1000 m row, 200 m farmer carry (45 DBs), 50 m waiter walk L (45), 50 m waiter walk R (45).","hero"],
  ["Gator","RFT",["Barbell","Bodyweight"],"8 rounds: 5 front squats (185), 26 ring push-ups.","hero"],
  ["Stephen","For Time",["Bodyweight","Barbell","Pull-up bar"],"30-25-20-15-10-5: GHD sit-ups, back extensions, knees-to-elbow, stiff-legged deadlifts (95).","hero"],
  ["Ledesma","RFT",["Bodyweight","Pull-up bar","Wall ball"],"6 rounds: 5 parallette HSPU, 10 toes-through-rings, 15 medicine-ball cleans (20).","hero"],
  ["Bradley","Interval",["Bodyweight","Pull-up bar"],"10 rounds: 100 m sprint, 10 pull-ups, 100 m sprint, 10 burpees — rest 30 s.","hero"],
  ["McCluskey","RFT",["Pull-up bar","Bodyweight"],"3 rounds: 9 muscle-ups, 15 burpee pull-ups, 21 pull-ups, 800 m run.","hero"],
  ["DG","RFT",["Pull-up bar","Dumbbells"],"10 rounds: 8 toes-to-bar, 8 DB thrusters (35), 12 DB walking lunges (35).","hero"],
  ["Brian","RFT",["Pull-up bar","Barbell"],"3 rounds: 5 rope climbs (15 ft), 25 back squats (185).","hero"],
  ["Thompson","RFT",["Pull-up bar","Barbell"],"10 rounds: 1 rope climb (15 ft), 29 back squats (95), 10 m barbell farmer carry (135/hand).","hero"],
  ["Kalsu","For Time",["Barbell","Bodyweight"],"100 thrusters (135) for time — start each minute (incl. min 0) with 5 burpees, then thrusters.","hero"],

  // ============ CROSSFIT OPEN — every year, 2011–2025 ============
  // 2011
  ["Open 11.1","AMRAP",["Jump rope","Barbell"],"10 min AMRAP: 30 double-unders, 15 power snatches (75).","open"],
  ["Open 11.2","AMRAP",["Barbell","Bodyweight","Box"],"15 min AMRAP: 9 deadlifts (155), 12 push-ups, 15 box jumps (24).","open"],
  ["Open 11.3","AMRAP",["Barbell"],"5 min AMRAP: max squat clean & jerks (165).","open"],
  ["Open 11.4","AMRAP",["Bodyweight","Barbell","Pull-up bar"],"10 min AMRAP: 60 bar-facing burpees, 30 OHS (120), 10 muscle-ups.","open"],
  ["Open 11.5","AMRAP",["Barbell","Pull-up bar","Wall ball"],"20 min AMRAP: 5 power cleans (145), 10 toes-to-bar, 15 wall balls (20).","open"],
  ["Open 11.6","AMRAP",["Barbell","Pull-up bar"],"7 min AMRAP ladder: 3-6-9… thrusters (100) + chest-to-bar pull-ups, +3 each round.","open"],
  // 2012
  ["Open 12.1","AMRAP",["Bodyweight"],"7 min AMRAP: burpees (jump and touch a target 6 in overhead).","open"],
  ["Open 12.2","AMRAP",["Barbell"],"10 min AMRAP: 30 snatches (75), 30 (135), 30 (165), then max snatches (210).","open"],
  ["Open 12.3","AMRAP",["Box","Barbell","Pull-up bar"],"18 min AMRAP: 15 box jumps (24), 12 push press (115), 9 toes-to-bar.","open"],
  ["Open 12.4","AMRAP",["Wall ball","Jump rope","Pull-up bar"],"12 min AMRAP: 150 wall balls (20), 90 double-unders, 30 muscle-ups.","open"],
  ["Open 12.5","AMRAP",["Barbell","Pull-up bar"],"7 min AMRAP ladder: 3-6-9… thrusters (100) + chest-to-bar pull-ups, +3 each round.","open"],
  // 2013
  ["Open 13.1","AMRAP",["Bodyweight","Barbell"],"17 min AMRAP: 40 burpees, 30 snatches (75), 30 burpees, 30 snatches (135), 20 burpees, 30 snatches (165), 10 burpees, max snatches (210).","open"],
  ["Open 13.2","AMRAP",["Barbell","Box"],"10 min AMRAP: 5 shoulder-to-overhead (115), 10 deadlifts (115), 15 box jumps (24).","open"],
  ["Open 13.3","AMRAP",["Wall ball","Jump rope","Pull-up bar"],"12 min AMRAP: 150 wall balls (20), 90 double-unders, 30 muscle-ups.","open"],
  ["Open 13.4","AMRAP",["Barbell","Pull-up bar"],"7 min AMRAP ladder: 3-3-6-6… clean & jerks (135) + toes-to-bar, +3 each.","open"],
  ["Open 13.5","For Time",["Barbell","Pull-up bar"],"4 min couplet: 15 thrusters (100) + 15 chest-to-bar; hit 90 reps to earn 4 more min (and so on).","open"],
  // 2014
  ["Open 14.1","AMRAP",["Jump rope","Barbell"],"10 min AMRAP: 30 double-unders, 15 power snatches (75).","open"],
  ["Open 14.2","AMRAP",["Barbell","Pull-up bar"],"Every 3 min: 2 rounds of 10 OHS (95) + 10 C2B, then +2 reps per round until you stall.","open"],
  ["Open 14.3","AMRAP",["Barbell","Box"],"8 min AMRAP: 10 deadlifts (135) + 15 box jumps (24); deadlift climbs 185/225/275/315, 15 box jumps each.","open"],
  ["Open 14.4","AMRAP",["Rower","Pull-up bar","Wall ball","Barbell"],"14 min AMRAP chipper: 60-cal row, 50 toes-to-bar, 40 wall balls (20), 30 cleans (135), 20 muscle-ups.","open"],
  ["Open 14.5","For Time",["Barbell","Bodyweight"],"21-18-15-12-9-6-3: thrusters (95) + bar-facing burpees. No time cap.","open"],
  // 2015
  ["Open 15.1","AMRAP",["Pull-up bar","Barbell"],"9 min AMRAP: 15 toes-to-bar, 10 deadlifts (115), 5 snatches (115). Then 15.1a: 6 min to a 1RM clean & jerk.","open"],
  ["Open 15.2","AMRAP",["Barbell","Pull-up bar"],"Every 3 min: 2 rounds of 10 OHS (95) + 10 C2B, +2 reps per round until you stall.","open"],
  ["Open 15.3","AMRAP",["Pull-up bar","Wall ball","Jump rope"],"14 min AMRAP: 7 muscle-ups, 50 wall balls (20), 100 double-unders.","open"],
  ["Open 15.4","AMRAP",["Bodyweight","Barbell"],"8 min AMRAP ladder: 3-6-9… HSPU + cleans (185), cleans climb every 3 rounds.","open"],
  ["Open 15.5","For Time",["Rower","Barbell"],"27-21-15-9: row (cals) + thrusters (95).","open"],
  // 2016
  ["Open 16.1","AMRAP",["Barbell","Bodyweight","Pull-up bar"],"20 min AMRAP: 25-ft OH walking lunge (95), 8 bar-facing burpees, 25-ft OH lunge, 8 chest-to-bar.","open"],
  ["Open 16.2","AMRAP",["Pull-up bar","Jump rope","Barbell"],"Ascending 4-min blocks: 25 toes-to-bar, 50 DU, then 15/13/11/9/7 squat cleans climbing 135→315.","open"],
  ["Open 16.3","AMRAP",["Barbell","Pull-up bar"],"7 min AMRAP: 10 power snatches (75), 3 bar muscle-ups.","open"],
  ["Open 16.4","AMRAP",["Barbell","Wall ball","Rower","Bodyweight"],"13 min AMRAP: 55 deadlifts (225), 55 wall balls (20), 55-cal row, 55 HSPU.","open"],
  ["Open 16.5","For Time",["Barbell","Bodyweight"],"21-18-15-12-9-6-3: thrusters (95) + bar-facing burpees.","open"],
  // 2017
  ["Open 17.1","For Time",["Dumbbells","Box"],"20 min cap: 10-20-30-40-50 DB snatches (50) with 15 burpee box jump-overs (24) after each set.","open"],
  ["Open 17.2","AMRAP",["Dumbbells","Pull-up bar"],"12 min AMRAP: 2 rounds [50-ft DB lunge (50s), 16 toes-to-bar, 8 DB power cleans], then sub bar muscle-ups for T2B.","open"],
  ["Open 17.3","For Time",["Pull-up bar","Barbell"],"Escalating caps: 3 rounds of 6 chest-to-bar + 6 squat snatches (95), then heavier snatches / more reps as you advance.","open"],
  ["Open 17.4","AMRAP",["Barbell","Wall ball","Rower","Bodyweight"],"13 min AMRAP: 55 deadlifts (225), 55 wall balls (20), 55-cal row, 55 HSPU.","open"],
  ["Open 17.5","RFT",["Barbell","Jump rope"],"10 rounds: 9 thrusters (95), 35 double-unders.","open"],
  // 2018
  ["Open 18.1","AMRAP",["Pull-up bar","Dumbbells","Rower"],"20 min AMRAP: 8 toes-to-bar, 10 DB hang clean & jerk (50), 14-cal row.","open"],
  ["Open 18.2","For Time",["Dumbbells","Bodyweight","Barbell"],"For time: 1-2-3…10 DB squats (50s) + bar-facing burpees; then 18.2a: build to a 1RM clean (12 min total).","open"],
  ["Open 18.3","For Time",["Jump rope","Barbell","Pull-up bar","Dumbbells"],"14 min cap, 2 rounds: 100 DU, 20 OHS (115), 100 DU, 12 ring muscle-ups, 100 DU, 20 DB snatches (50), 100 DU, 12 bar muscle-ups.","open"],
  ["Open 18.4","For Time",["Barbell","Bodyweight"],"9 min cap: 21-15-9 deadlifts (225) + HSPU, then 21-15-9 deadlifts (315) + 50-ft handstand walks.","open"],
  ["Open 18.5","AMRAP",["Barbell","Pull-up bar"],"7 min AMRAP ladder: 3-6-9… thrusters (100) + chest-to-bar pull-ups.","open"],
  // 2019
  ["Open 19.1","AMRAP",["Wall ball","Rower"],"15 min AMRAP: 19 wall balls (20), 19-cal row.","open"],
  ["Open 19.2","AMRAP",["Pull-up bar","Jump rope","Barbell"],"Ascending 4-min blocks: 25 toes-to-bar, 50 DU, 15/13/11/9/7 squat cleans 135→315.","open"],
  ["Open 19.3","For Time",["Dumbbells","Box","Bodyweight"],"10 min cap: 200-ft DB OH lunge (50), 50 DB box step-ups (24), 50 strict HSPU, 200-ft handstand walk.","open"],
  ["Open 19.4","For Time",["Barbell","Bodyweight","Pull-up bar"],"12 min cap: 3 rounds [10 snatches (95), 12 bar-facing burpees], rest 3 min, 3 rounds [10 bar muscle-ups, 12 burpees].","open"],
  ["Open 19.5","For Time",["Barbell","Pull-up bar"],"20 min cap: 33-27-21-15-9 thrusters (95) + chest-to-bar pull-ups.","open"],
  // 2020
  ["Open 20.1","RFT",["Barbell","Bodyweight"],"15 min cap, 10 rounds: 8 ground-to-overhead (95), 10 bar-facing burpees.","open"],
  ["Open 20.2","AMRAP",["Dumbbells","Pull-up bar","Jump rope"],"20 min AMRAP: 4 DB thrusters (50s), 6 toes-to-bar, 24 double-unders.","open"],
  ["Open 20.3","For Time",["Barbell","Bodyweight"],"9 min cap: 21-15-9 deadlifts (225) + HSPU, then 21-15-9 deadlifts (315) + 50-ft handstand walks.","open"],
  ["Open 20.4","For Time",["Box","Barbell","Bodyweight"],"20 min cap: 30 box jumps (24) + clean & jerks climbing 95→315, with single-leg squats replacing box jumps mid-way.","open"],
  ["Open 20.5","For Time",["Pull-up bar","Rower","Wall ball"],"20 min cap, any order: 40 muscle-ups, 80-cal row, 120 wall balls (20).","open"],
  // 2021
  ["Open 21.1","For Time",["Bodyweight","Jump rope"],"15 min cap, ascending: 1 wall walk + 10 DU, 3+30, 6+60, 9+90, 15+150, 21+210.","open"],
  ["Open 21.2","For Time",["Dumbbells","Box"],"20 min cap: 10-20-30-40-50 DB snatches (50) with 15 burpee box jump-overs (24) after each set.","open"],
  ["Open 21.3","For Time",["Barbell","Pull-up bar"],"Time caps: 15 front squats (95), 30 toes-to-bar, 15 thrusters; repeat subbing C2B, then bar muscle-ups.","open"],
  ["Open 21.4","For Time",["Barbell"],"Right after 21.3: 7 min to build a 1RM complex — deadlift + clean + hang clean + jerk.","open"],
  // 2022
  ["Open 22.1","AMRAP",["Bodyweight","Dumbbells","Box"],"15 min AMRAP: 3 wall walks, 12 DB snatches (50), 15 box jump-overs (24).","open"],
  ["Open 22.2","For Time",["Barbell","Bodyweight"],"10 min cap: 1-2-3…10-9…1 ladder of deadlifts (225) + bar-facing burpees.","open"],
  ["Open 22.3","For Time",["Pull-up bar","Jump rope","Barbell"],"12 min cap: 21 pull-ups, 42 DU, 21 thrusters (95); 18 C2B, 36 DU, 18 thrusters (115); 15 bar MU, 30 DU, 15 thrusters (135).","open"],
  // 2023
  ["Open 23.1","AMRAP",["Rower","Pull-up bar","Wall ball","Barbell"],"14 min AMRAP: 60-cal row, 50 toes-to-bar, 40 wall balls (20), 30 cleans (135), 20 muscle-ups.","open"],
  ["Open 23.2","AMRAP",["Pull-up bar","Bodyweight","Barbell"],"23.2a: 15 min AMRAP — ascending 5 burpee pull-ups + 10 shuttle runs (+5 burpee pull-ups each round). 23.2b: 5 min to a 1RM thruster.","open"],
  ["Open 23.3","For Time",["Bodyweight","Jump rope","Barbell"],"Progressive caps: 5 wall walks, 50 DU, 15 snatches (95); 5 ww, 50 DU, 12 snatches (135); then 20 strict HSPU, 50 DU, 9 snatches (185); then 6 snatches (225).","open"],
  // 2024
  ["Open 24.1","For Time",["Dumbbells","Bodyweight"],"15 min cap: 21-15-9 (per arm) DB snatches (50) with 21-15-9 lateral burpees over the DB between arms.","open"],
  ["Open 24.2","AMRAP",["Rower","Barbell","Jump rope"],"20 min AMRAP: 300 m row, 10 deadlifts (185), 50 double-unders.","open"],
  ["Open 24.3","For Time",["Barbell","Pull-up bar"],"15 min cap: 5 rounds [10 thrusters (95), 10 chest-to-bar], rest 1 min, 5 rounds [7 thrusters (135), 7 bar muscle-ups].","open"],
  // 2025
  ["Open 25.1","AMRAP",["Dumbbells","Bodyweight"],"15 min AMRAP, ascending: 3 lateral burpees over DB + 3 DB hang clean-to-overhead (50) + 30-ft walking lunge; +3 reps each round.","open"],
  ["Open 25.2","For Time",["Pull-up bar","Jump rope","Barbell"],"12 min cap: 21 pull-ups, 42 DU, 21 thrusters (95); 18 C2B, 36 DU, 18 thrusters (115); 15 bar MU, 30 DU, 15 thrusters (135).","open"],
  ["Open 25.3","For Time",["Bodyweight","Rower","Barbell"],"20 min cap: wall walks, two 50-cal rows, and a barbell ladder of deadlifts → cleans → snatches (25 reps each).","open"],

  // ============ OTHER / minimal-equipment / formats ============
  ["Triple 3","For Time",["Rower","Jump rope","Bodyweight"],"3000 m row, 300 double-unders, 3 mi run. A Games-style engine test.","other"],
  ["CrossFit Total","For Time",["Barbell"],"Best of 3 attempts each: 1RM back squat + 1RM shoulder press + 1RM deadlift. Score = the sum.","other"],
  ["Fight Gone Bad","For Time",["Wall ball","Barbell","Box","Rower"],"3 rounds, 5 stations × 1 min: wall ball (20), SDHP (75), box jump (20), push press (75), row (cals). 1 min rest between rounds.","other"],
  ["Filthy Fifty","Chipper",["Box","Pull-up bar","Kettlebell","Wall ball","Jump rope"],"50 reps each: box jumps, jumping pull-ups, KB swings, walking lunges, knees-to-elbow, push press (45), back ext, wall balls, burpees, double-unders.","other"],
  ["Tabata This","Tabata",["Bodyweight","Rower","Pull-up bar"],"Tabata (20s on/10s off ×8) of row, squats, pull-ups, push-ups, sit-ups. Lowest round scores each.","other"],
  ["The Ghost","AMRAP",["Rower","Jump rope","Bodyweight"],"6 rounds: 1 min max-cal row, 1 min max burpees, 1 min max double-unders — rest 1 min between rounds.","other"],
  ["Cindy XXL","AMRAP",["Pull-up bar","Bodyweight"],"30 min Cindy: 5 pull-ups, 10 push-ups, 15 squats.","other"],
  ["DB Fran","For Time",["Dumbbells","Pull-up bar"],"21-15-9: dumbbell thrusters + pull-ups.","other"],
  ["DB EMOM","EMOM",["Dumbbells"],"20 min EMOM — odd: 10 DB snatches, even: 10 DB thrusters.","other"],
  ["DB Chipper","Chipper",["Dumbbells","Box"],"50 DB snatches, 40 box jumps, 30 DB thrusters, 20 burpees, 10 DB clusters.","other"],
  ["KB AMRAP","AMRAP",["Kettlebell"],"15 min AMRAP: 10 KB swings, 10 goblet squats, 10 push-ups.","other"],
  ["KB EMOM","EMOM",["Kettlebell"],"16 min EMOM — odd: 15 swings, even: 12 goblet squats.","other"],
  ["Death by Burpees","Interval",["Bodyweight"],"Min 1: 1 burpee, +1 each minute until you can't finish in the minute.","other"],
  ["100 Burpees","For Time",["Bodyweight"],"100 burpees for time. Steady pace beats sprinting.","other"],
  ["Tabata Squats","Tabata",["Bodyweight"],"8 rounds, 20s on / 10s off air squats. Count your lowest round.","other"],
  ["Tabata Mix","Tabata",["Bodyweight"],"4 movements × 8 rounds (20/10): squats, push-ups, mountain climbers, hollow rocks.","other"],
  ["Run Ladder","Ladder",["Bodyweight"],"200-400-800-400-200 m run; 1-2-3-2-1 rounds of a triplet between each.","other"],
  ["5K Run","For Time",["Bodyweight"],"5 km run for time. Negative-split it.","other"],
  ["Row Sprints","Interval",["Rower"],"8 × 250 m row, rest 1 min. Hold an even pace.","other"],
  ["Box Jump EMOM","EMOM",["Box"],"10 min EMOM: 10 box jumps each minute (step down).","other"],
  ["Slam Ball Chipper","Chipper",["Slam ball","Box"],"800 m run, 40 slam balls, 30 DB snatches, 20 box jumps, 800 m run.","other"],
  ["21-15-9 Couplet","For Time",["Bodyweight"],"Pick any two movements, 21-15-9 for time (e.g. thrusters + burpees).","other"],
  ["AMRAP 20","AMRAP",["Bodyweight"],"Build your own 20 min AMRAP from 3 movements you choose.","other"],
  ["EMOM 24","EMOM",["Bodyweight"],"24 min, rotate 3 movements each minute (8 rounds).","other"]
];
